// Do not edit. This file is machine generated by the Resource DLL Wizard.

library MineSwapper;

{ITE} {DFMFileType} {uCustomForm.dfm}
{ITE} {DFMFileType} {uMain.dfm}
{ITE} {RCFileType} {Win32\Debug\MineSwapper_DRC.rc}

{$R 'uCustomForm.dfm' fmCustomForm:TForm}
{$R 'uMain.dfm' fmMain:TForm}
{$R 'Win32\Debug\MineSwapper_DRC.res' 'Win32\Debug\MineSwapper_DRC.rc'}

{$E PLK}

begin
end.
